Revert "win7 compat"
This reverts commit 56f3512738dfcdcfffc4010a3ce6100e3a6e35f9.

Removing CreateFile2 calls was insufficient to enable win7 support.
There are win8+ API calls which are not straightforward to replace:

    onnxruntime\core\platform\windows\env_time.cc(31): error C2065: 'GetSystemTimePreciseAsFileTime': undeclared identifier